/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class ContactInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactInfo
     */
    StaffPersInfo p;
    public ContactInfo(StaffPersInfo s) {
        this.p=s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mobileNumb = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        town = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        state = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        phoneNumb = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        streetName = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        plotNmb = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Contact Information");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("STAFF INFORMATION");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Contact Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mobileNumb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(mobileNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Street Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText(" City/Town");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        town.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Mobile No");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("   State");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        state.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        state.setForeground(java.awt.Color.darkGray);
        state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo ", "Ekiti", "Enugu", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Kastina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nassarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara" }));
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        jPanel2.add(state, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 130, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 51, 51));
        jLabel28.setText("*");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 10, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("*");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 10, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("*");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 10, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 51, 51));
        jLabel32.setText("*");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 10, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 51));
        jLabel34.setText("*");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 10, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 51, 51));
        jLabel35.setText(" *");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 20, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 51));
        jLabel11.setText("House Plot No");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 51));
        jLabel12.setText(" Phone No");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        phoneNumb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(phoneNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 190, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 51));
        jLabel13.setText("Email Address");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        emailAddress.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 190, 20));

        streetName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(streetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 260, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setText("*");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 10, 20));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 51, 51));
        jLabel38.setText("*");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 10, 20));

        next.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        next.setText("Next");
        next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel2.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 150, 35));

        plotNmb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(plotNmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 560, 230));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, 10));

        cancel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 150, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getStaffID(){
        return p.getStaffID();
    }
    
    public void insert() throws Exception{
        p.insert();

        PreparedStatement st;

        String sql="insert into staff_contact_info (staff_id, house_no, street_name, city, state, mobile, phone, email) values (?,?,?,?,?,?,?,?)";
        st= DBConnection.con.prepareStatement(sql);
        st.setString(1, ""+p.getStaffID());
        st.setString(2, plotNmb.getText());
        st.setString(3, streetName.getText());
        st.setString(4, town.getText());
        st.setString(5, ""+state.getSelectedItem());
        st.setString(6, ""+mobileNumb.getText());
        st.setString(7, phoneNumb.getText());
        st.setString(8, ""+emailAddress.getText());

        st.executeUpdate();
        System.out.println("Done2");
    }
    
    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
        DBConnection db = new DBConnection(){
            
        };
    }//GEN-LAST:event_stateActionPerformed
    private KinInfo kin;
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if(plotNmb.getText().equals("") || streetName.getText().equals("") ||
                state.getSelectedIndex()==0 || town.getText().equals("")||
                mobileNumb.getText().equals("") || phoneNumb.getText().equals("") ||
                emailAddress.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            Thread runner = new Thread() {

                public void run() {
                    kin = new KinInfo(ContactInfo.this);
                    MainMenu.desktop1.add(kin);
                try {
                    kin.setSelected(true);
                } catch (java.beans.PropertyVetoException e) {
                }
                }
                    };
                runner.start();
                this.dispose();
        }
    }//GEN-LAST:event_nextActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    public static javax.swing.JTextField emailAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField mobileNumb;
    private javax.swing.JButton next;
    public static javax.swing.JTextField phoneNumb;
    public static javax.swing.JTextField plotNmb;
    public static javax.swing.JComboBox state;
    public static javax.swing.JTextField streetName;
    public static javax.swing.JTextField town;
    // End of variables declaration//GEN-END:variables
}
