/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import static com.ecs.MainMenu.desktop1;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class EditEducationInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form EducationInfo
     */
    public EditEducationInfo() {
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        course = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        certificate = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        schoolAtt = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        yy = new com.toedter.calendar.JYearChooser();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        postGradCert = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        prof_cert = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        staffId = new javax.swing.JFormattedTextField();
        validate = new javax.swing.JButton();
        select5 = new javax.swing.JButton();
        select2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Educational Information");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user35.jpg"))); // NOI18N
        setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Educational Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        course.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("  Certification");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Year of Certification");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("  School attended");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        certificate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        certificate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "FSLC", "SSCE", "ND", "NCE", "HND", "BSC" }));
        jPanel1.add(certificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 120, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Course of Study");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 51, 51));
        jLabel31.setText("*");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 10, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 51, 51));
        jLabel33.setText("*");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 10, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 51, 51));
        jLabel35.setText("*");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 10, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 51));
        jLabel11.setText("Address of School Line");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        schoolAtt.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(schoolAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 280, 20));

        update.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        update.setText("Update the Information");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 220, 30));
        jPanel1.add(yy, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 51));
        jLabel34.setText("*");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 30, 20));

        address.setColumns(20);
        address.setRows(2);
        address.setTabSize(4);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 280, 50));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("*");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 20, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 51));
        jLabel9.setText(" Post Grad Certs");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        postGradCert.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(postGradCert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 51, 51));
        jLabel36.setText("*");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 10, 20));

        prof_cert.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(prof_cert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 190, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Professional Certificates");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 480, 320));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("STAFF INFORMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 520, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Search Staff", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 51));
        jLabel14.setText("Staff ID");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 30));

        staffId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        staffId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 190, -1));

        validate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        validate.setText("Validate");
        validate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });
        jPanel3.add(validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 90, 30));

        select5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select5.setText("Refresh");
        select5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select5ActionPerformed(evt);
            }
        });
        jPanel3.add(select5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 100));

        select2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select2.setText("Cancel");
        select2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select2ActionPerformed(evt);
            }
        });
        jPanel2.add(select2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        if(staffId.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql="select * from staff_education_info where staff_id=?";
                st=DBConnection.con.prepareStatement(sql);
                st.setString(1, staffId.getText().trim());
                DBConnection.rs=st.executeQuery();
                if(DBConnection.rs.next()){
                    yy.setYear(DBConnection.rs.getInt("year"));
                    schoolAtt.setText(DBConnection.rs.getString("sch_attended"));
                    address.setText(DBConnection.rs.getString("address"));
                    certificate.setSelectedItem(DBConnection.rs.getString("certification"));
                    course.setText(""+DBConnection.rs.getString("course_of_study"));
                    postGradCert.setText(""+DBConnection.rs.getString("post_grad_certs"));
                    
                    this.staffId.setEnabled(false);
                    validate.setEnabled(false);
                    update.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Staff ID does not exist","Issues!", JOptionPane.OK_OPTION);
                }
            }catch(SQLException sqlEx){
                JOptionPane.showMessageDialog(this, "Issues excecuting query","Issues!", JOptionPane.OK_OPTION);
                System.err.println(sqlEx.getMessage());
                refresh();
            } 
        }
    }//GEN-LAST:event_validateActionPerformed

    private void select5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select5ActionPerformed
        refresh();
    }//GEN-LAST:event_select5ActionPerformed

    private void select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select2ActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_select2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(yy.getYear()==0 || staffId.getText().equals("") || certificate.getSelectedIndex()==0 || address.getText().equals("") || course.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql="update staff_education_info set certification=?, year=?, sch_attended=?, address=?, course_of_study=?, post_grad_certs = ? where staff_id=?";
                st= DBConnection.con.prepareStatement(sql);
                
                st.setString(1, ""+certificate.getSelectedItem());
                st.setString(2, ""+yy.getYear());
                st.setString(3, schoolAtt.getText());
                st.setString(4, address.getText());
                st.setString(5, course.getText());
                st.setString(6, postGradCert.getText());
                st.setString(7, staffId.getText());
                st.executeUpdate();

                JOptionPane.showMessageDialog(this, "Staff Information Updated","Success!", JOptionPane.INFORMATION_MESSAGE);
                //Refresh page
                refresh();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Issues excecuting query","Issues!", JOptionPane.OK_OPTION);
                System.err.println(ex.getMessage());
            }finally{
                DBConnection.rs=null;
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                EditEducationInfo mandate1 = new EditEducationInfo();
                desktop1.add(mandate1);
                try {
                    mandate1.setSelected(true);
                }catch (java.beans.PropertyVetoException e) {
                }
            }
        };
        runner.start();
        
        this.dispose();
        this.hide();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    public static javax.swing.JComboBox certificate;
    public static javax.swing.JTextField course;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField postGradCert;
    public static javax.swing.JTextField prof_cert;
    public static javax.swing.JTextField schoolAtt;
    private javax.swing.JButton select2;
    private javax.swing.JButton select5;
    public static javax.swing.JFormattedTextField staffId;
    private javax.swing.JButton update;
    private javax.swing.JButton validate;
    private com.toedter.calendar.JYearChooser yy;
    // End of variables declaration//GEN-END:variables
}
