/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import static com.ecs.MainMenu.desktop1;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class EditStaffAccInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form StaffAccInfo
     */
    public EditStaffAccInfo() {
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        acctName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bank = new javax.swing.JComboBox();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pay = new javax.swing.JFormattedTextField();
        sortCode = new javax.swing.JTextField();
        acctNumb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        staffId = new javax.swing.JFormattedTextField();
        select5 = new javax.swing.JButton();
        validate = new javax.swing.JButton();
        select6 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Staff Bank Account Details");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 320, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)), "Staff Bank Account Deteils", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.darkGray)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText(" Acct Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Acct Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Bank Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        acctName.setEditable(false);
        acctName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(acctName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 170, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Sort Code");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        bank.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        bank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Bank", "Eco Bank", "First Bank", "GTBank", "MainStreet Bank" }));
        jPanel1.add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 170, -1));

        update.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        update.setText("Update the Information");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 220, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText(" Staff Hourly Pay");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 40));

        pay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 20));

        sortCode.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(sortCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 20));

        acctNumb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(acctNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 220));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("STAFF INFORMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Search Staff", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 51));
        jLabel14.setText("Staff ID");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

        staffId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        staffId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, 30));

        select5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select5.setText("Refresh");
        select5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select5ActionPerformed(evt);
            }
        });
        jPanel3.add(select5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, 30));

        validate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        validate.setText("Validate");
        validate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });
        jPanel3.add(validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, 100));

        select6.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select6.setText("Cancel");
        select6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select6ActionPerformed(evt);
            }
        });
        jPanel2.add(select6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select5ActionPerformed
        refresh();
    }//GEN-LAST:event_select5ActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                EditStaffAccInfo mandate1 = new EditStaffAccInfo();
                desktop1.add(mandate1);
                try {
                    mandate1.setSelected(true);
                }catch (java.beans.PropertyVetoException e) {
                }
            }
        };
        runner.start();
        
        this.dispose();
        this.hide();
    }
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(staffId.getText().equals("") || acctName.getText().equals("") ||
                bank.getSelectedIndex()==0 || acctNumb.getText().equals("")
                || sortCode.getText().equals("") || pay.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql="update staff_acct_info set acct_numb=?, bank_name=?, sort_code=?, staff_hourly_pay=? where staff_id=?";
                st= DBConnection.con.prepareStatement(sql);
                
                st.setString(1, ""+Integer.parseInt(acctNumb.getText()));
                st.setString(2, ""+bank.getSelectedItem());
                st.setString(3, ""+Integer.parseInt(sortCode.getText()));
                st.setDouble(4, Double.parseDouble(pay.getText()));
                st.setString(5, staffId.getText());
                st.executeUpdate();

                JOptionPane.showMessageDialog(this, "Staff Information Updated","Success!", JOptionPane.INFORMATION_MESSAGE);
                //Refresh page
                st.executeUpdate();
                refresh();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Issues excecuting query","Issues!", JOptionPane.OK_OPTION);
                System.err.println(ex.getMessage());
            }catch(NumberFormatException nEx){
                JOptionPane.showMessageDialog(this, "Account number or sort code is incorrect","Issues!", JOptionPane.OK_OPTION);
            }finally{
                DBConnection.rs=null;
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void select6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select6ActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_select6ActionPerformed

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        if(staffId.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql="select * from staff_acct_info, staff_pers_info where staff_acct_info.staff_id=? AND staff_acct_info.staff_id = staff_pers_info.staff_id";
                st=DBConnection.con.prepareStatement(sql);
                st.setString(1, staffId.getText().trim());
                DBConnection.rs=st.executeQuery();
                if(DBConnection.rs.next()){
                    
                    acctName.setText(DBConnection.rs.getString("fname") + (DBConnection.rs.getString("mname").equals("") ? " ": " "+DBConnection.rs.getString("mname")+", ") + DBConnection.rs.getString("lname"));
                    acctNumb.setText(DBConnection.rs.getString("acct_numb"));
                    sortCode.setText(DBConnection.rs.getString("sort_code"));
                    bank.setSelectedItem(DBConnection.rs.getString("bank_name"));
                    pay.setText(DBConnection.rs.getString("staff_hourly_pay"));
                    
                    this.staffId.setEnabled(false);
                    validate.setEnabled(false);
                    update.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Staff ID does not exist","Issues!", JOptionPane.OK_OPTION);
                }
            }catch(SQLException sqlEx){
                JOptionPane.showMessageDialog(this, "Issues excecuting query","Issues!", JOptionPane.OK_OPTION);
                System.err.println(sqlEx.getMessage());
                refresh();
            }
        }
    }//GEN-LAST:event_validateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField acctName;
    public static javax.swing.JTextField acctNumb;
    private javax.swing.JComboBox bank;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JFormattedTextField pay;
    private javax.swing.JButton select5;
    private javax.swing.JButton select6;
    public static javax.swing.JTextField sortCode;
    public static javax.swing.JFormattedTextField staffId;
    private javax.swing.JButton update;
    private javax.swing.JButton validate;
    // End of variables declaration//GEN-END:variables
}
