/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import static com.ecs.MainMenu.desktop1;
import java.io.File;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class EditStaffPersInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form StaffPersInfo
     */
    public EditStaffPersInfo() {
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        middlename = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mstatus = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        religion = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        we2 = new javax.swing.JLabel();
        we3 = new javax.swing.JLabel();
        us = new javax.swing.JPanel();
        me = new javax.swing.JLabel();
        me1 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        update = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        staffId = new javax.swing.JFormattedTextField();
        validate = new javax.swing.JButton();
        select4 = new javax.swing.JButton();
        select2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Staff Personal Information");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Personal Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Religion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Firstname");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 30));

        firstname.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText(" Middlename");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        middlename.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText(" Surname");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 30));

        mstatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Single", "Married", "Divorced" }));
        jPanel1.add(mstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText(" Marital Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 40));

        religion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        religion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Islam", "Christian" }));
        jPanel1.add(religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText(" Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 40));

        surname.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 190, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText(" Date of Birth");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        gender.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select...", "Male", "Female" }));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 51, 51));
        jLabel28.setText("*");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 10, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("*");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 10, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 51, 51));
        jLabel31.setText("*");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 10, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 51));
        jLabel34.setText("*");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 10, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 51, 51));
        jLabel35.setText("*");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 10, 20));

        we2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        we2.setText("* Image must be .jpg");
        jPanel1.add(we2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 20));

        we3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        we3.setText("* Image must not be larger than 150px X 150px");
        jPanel1.add(we3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, 20));

        us.setBackground(new java.awt.Color(255, 255, 255));
        us.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 12, 92)));
        us.setMaximumSize(new java.awt.Dimension(150, 150));
        us.setMinimumSize(new java.awt.Dimension(150, 150));
        us.setPreferredSize(new java.awt.Dimension(150, 150));
        us.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        us.add(me, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        me1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                me1PropertyChange(evt);
            }
        });
        us.add(me1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        select.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select.setText("Select Passport");
        select.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        jPanel1.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 150, 35));

        update.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        update.setText("Update the Information");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 200, 35));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 190, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("*");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 10, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 580, 310));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("STAFF INFORMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 620, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Search Staff", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 51));
        jLabel14.setText("Staff ID");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 30));

        staffId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        staffId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 90, 30));

        validate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        validate.setText("Validate");
        validate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });
        jPanel3.add(validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, 35));

        select4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select4.setText("Refresh");
        select4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select4ActionPerformed(evt);
            }
        });
        jPanel3.add(select4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 35));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 110));

        select2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select2.setText("Cancel");
        select2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select2ActionPerformed(evt);
            }
        });
        jPanel2.add(select2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 110, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private ContactInfo conInfo;
    private void me1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_me1PropertyChange

    }//GEN-LAST:event_me1PropertyChange

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue;
        returnValue = fileChooser.showOpenDialog(this);
        if(returnValue== JFileChooser.APPROVE_OPTION){
            try{
                File file;
                file= fileChooser.getSelectedFile();
                String st= file.toString();
                int index=st.lastIndexOf('.');
                String test=st.substring(index+1);
                if(test.equals("jpg")){
                    Icon iicon= new ImageIcon(file.getPath());
                    int a= iicon.getIconHeight();
                    int b= iicon.getIconWidth();
                    if(a<=150 && b<=150){
                        me1.setIcon(iicon);
                    }else{
                        me1.setIcon(null);
                        JOptionPane.showMessageDialog(null, "Image must not be larger than 150px X 150px","Issue!", JOptionPane.OK_OPTION);
                    }
                }else{
                    me1.setIcon(null);
                    JOptionPane.showMessageDialog(null, "File is not .jpg format","Issue!", JOptionPane.OK_OPTION);
                }

            }catch(Exception ex){
                me1.setIcon(null);
            }

        }
    }//GEN-LAST:event_selectActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(staffId.getText().equals("") || firstname.getText().equals("") ||
                mstatus.getSelectedIndex()==0 || surname.getText().equals("")
                || dob.getDate() == null || surname.getText().equals("")
                || gender.getSelectedIndex()==0 || religion.getSelectedIndex()==0 || ""+me1.getIcon()==""){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
                String date = ft.format(dob.getDate());
                
               
                PreparedStatement st;
                
                String sql= "update staff_pers_info set lname=?, mname=?, fname=?, mstatus=?, gender=?, dob=?, religion=?, passport=? where staff_id=?";
                st = DBConnection.con.prepareStatement(sql);
                
                st.setString(1, surname.getText());
                st.setString(2, middlename.getText());
                st.setString(3, firstname.getText());
                st.setString(4, ""+mstatus.getSelectedItem());
                st.setString(5, ""+gender.getSelectedItem());
                st.setString(6, date);
                st.setString(7, ""+religion.getSelectedItem());
                st.setString(8, ""+me1.getIcon());
                st.setInt(9, Integer.parseInt(staffId.getText()));
                
                st.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Staff Information Updated",
                    "Updated", JOptionPane.INFORMATION_MESSAGE);
                refresh();
            }catch(Exception ex){
                ex.printStackTrace();
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select2ActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_select2ActionPerformed

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        if(staffId.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                String sql1= "select * from staff_pers_info where staff_id="+staffId.getText()+"";
                DBConnection.rs= DBConnection.st.executeQuery(sql1);
                if(DBConnection.rs.next()){
                    firstname.setText(""+DBConnection.rs.getString("fname"));
                    middlename.setText(DBConnection.rs.getString("mname"));
                    surname.setText(DBConnection.rs.getString("lname"));
                    mstatus.setSelectedItem(""+DBConnection.rs.getString("mstatus"));
                    gender.setSelectedItem(""+DBConnection.rs.getString("gender"));
                    religion.setSelectedItem(DBConnection.rs.getString("religion"));
                    String me= DBConnection.rs.getString("passport");
                    Icon iicon= new ImageIcon(me);
                    me1.setIcon(iicon);
                    dob.setDate(new java.util.Date(DBConnection.rs.getString("dob").replaceAll("-", "/")));
                    
                    staffId.setEnabled(false);
                    validate.setEnabled(false);
                    update.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Staff ID does not exist",
                        "Staff not found", JOptionPane.OK_OPTION);
                }
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_validateActionPerformed

    private void select4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select4ActionPerformed
        refresh();
    }//GEN-LAST:event_select4ActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                EditStaffPersInfo mandate1 = new EditStaffPersInfo();
                desktop1.add(mandate1);
                try {
                    mandate1.setSelected(true);
                }catch (java.beans.PropertyVetoException e) {
                }
            }
        };
        runner.start();
        
        this.dispose();
        this.hide();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dob;
    public static javax.swing.JTextField firstname;
    public static javax.swing.JComboBox gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel me;
    private javax.swing.JLabel me1;
    public static javax.swing.JTextField middlename;
    public static javax.swing.JComboBox mstatus;
    public static javax.swing.JComboBox religion;
    private javax.swing.JButton select;
    private javax.swing.JButton select2;
    private javax.swing.JButton select4;
    public static javax.swing.JFormattedTextField staffId;
    public static javax.swing.JTextField surname;
    private javax.swing.JButton update;
    private javax.swing.JPanel us;
    private javax.swing.JButton validate;
    private javax.swing.JLabel we2;
    private javax.swing.JLabel we3;
    // End of variables declaration//GEN-END:variables
}
