/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import com.dataStructures.PasswordHash;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu(){ 
        DBConnection.connect();
        initComponents();
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        //setSize(screenSize.width, screenSize.height - 30);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        iconm.setVisible(false);
        message.setVisible(false);
        jMenu4.setVisible(false);
        jMenu3.setVisible(false);
        jMenu7.setVisible(false);
        jMenuItem1.setVisible(false);
        jMenu6.setVisible(false);
        jLabel1.setVisible(false);
        jMenu5.setVisible(false);
    }

    public void adminControls(){
        jMenu3.setVisible(true);
        jMenu7.setVisible(true);
        jMenu6.setVisible(true);
        jMenu4.setVisible(true);
        jMenuItem1.setVisible(true);
        jLabel1.setVisible(true);
        jMenu5.setVisible(true);
    }
    
    public void techUserControls(){
        jMenu3.setVisible(true);
        jMenu7.setVisible(true);
        jMenu6.setVisible(true);
        jMenu4.setVisible(true);
        jMenuItem1.setVisible(true);
        jLabel1.setVisible(true);
        jMenu5.setVisible(true);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        iconm = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Clocking System");
        setMinimumSize(new java.awt.Dimension(604, 492));

        desktop1.setBackground(new java.awt.Color(255, 255, 255));
        desktop1.setPreferredSize(new java.awt.Dimension(880, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 90, -1));

        username.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 300, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Copyright 2018'");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 190, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-387-log-in.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(40);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 150, 40));

        password.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 300, 30));

        iconm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/ajax-loader2.gif"))); // NOI18N
        jPanel1.add(iconm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 50, -1));

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.setForeground(new java.awt.Color(0, 102, 0));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Validating User...");
        message.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        message.setIconTextGap(19);
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 230, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/payroll_banner1.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 430, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jLabel5.setText("LOGIN INFORMATION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/NNPC-e1491333545387.jpg"))); // NOI18N

        desktop1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGap(442, 442, 442)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktop1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 28));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 34));

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(0, 102, 0));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setIconTextGap(10);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-388-log-out.png"))); // NOI18N
        jMenuItem1.setText("Logout");
        jMenuItem1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jMenuItem1.setIconTextGap(10);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-389-exit.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(0, 0, 0));
        jMenu3.setForeground(new java.awt.Color(0, 102, 0));
        jMenu3.setText("Add");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setIconTextGap(10);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        jMenuItem6.setText("New Staff");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu6.setBackground(new java.awt.Color(0, 0, 0));
        jMenu6.setForeground(new java.awt.Color(0, 102, 0));
        jMenu6.setText("Edit");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.setIconTextGap(10);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Edit16.gif"))); // NOI18N
        jMenuItem16.setText("Edit Staff Personall Info");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Edit16.gif"))); // NOI18N
        jMenuItem7.setText("Edit Staff Contact Info");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Edit16.gif"))); // NOI18N
        jMenuItem13.setText("Edit Staff Education Info");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Edit16.gif"))); // NOI18N
        jMenuItem14.setText("Edit Staff Next of Kin Info");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Edit16.gif"))); // NOI18N
        jMenuItem15.setText("Edit Staff Account Info");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuBar1.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(0, 0, 0));
        jMenu7.setForeground(new java.awt.Color(0, 102, 0));
        jMenu7.setText("Perform");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu7.setIconTextGap(10);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem18.setText("Record Staff Sign In");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuItem30.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem30.setText("Record Staff Sign Out");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem30);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem20.setText("Pay Staffs (Personal)");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuBar1.add(jMenu7);

        jMenu5.setBackground(new java.awt.Color(0, 0, 0));
        jMenu5.setForeground(new java.awt.Color(0, 102, 0));
        jMenu5.setText("Staff Report");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu5.setIconTextGap(10);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem12.setText("View Staff Payments");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem27.setText("View Staff Clockings");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem27);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem26.setText("View Staff Monument Balance");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem26);

        jMenuBar1.add(jMenu5);

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setForeground(new java.awt.Color(0, 102, 0));
        jMenu4.setText("General Report");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu4.setIconTextGap(10);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem10.setText("View all Staffs");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem11.setText("View Staffs Payments");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem28.setText("View Staffs Clocking");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/List16.gif"))); // NOI18N
        jMenuItem29.setText("View Staffs Monument Balances");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem29);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String usertype;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setCursor(Cursor.WAIT_CURSOR);
        int option=JOptionPane.showConfirmDialog(this,"Are You sure You want to "
                + "Exit", "Exit", JOptionPane.YES_NO_OPTION);
        if (option ==0){
            System.exit(0);
        }
        else{

        }
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(username.getText()) || "".equals(password.getText())){
            JOptionPane.showMessageDialog(this,"Empty fields, try again","Empty Field", JOptionPane.OK_OPTION);
        }else{
            Thread runner = new Thread() {
                public void run() {
                    message.setForeground(new java.awt.Color(0, 102, 0));
                    message.setText("Validating User...");
                    try {
                        message.setVisible(true);
                        iconm.setVisible(true);
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }
                    String pass="";
                    String user="";
                    try{
                        String sql1= "select * from User where Username='"+username.getText()+"'";
                        DBConnection.rs= DBConnection.st.executeQuery(sql1);
                        if(DBConnection.rs.next()){
                            pass=DBConnection.rs.getString("Password");
                            user=DBConnection.rs.getString("Username");
                            usertype=DBConnection.rs.getString("Usertype");
                        }
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null,ex.getMessage());
                    }
                    if (pass.equals((new PasswordHash()).getSecurePassword(password.getText())) && user.equalsIgnoreCase(username.getText()) ){
                        Thread runner2 = new Thread() {
                            public void run() {
                                message.setForeground(new java.awt.Color(0, 102, 0));
                                message.setText("Login Successful, Opening...");
                                try {
                                    message.setVisible(true);
                                    iconm.setVisible(true);
                                    Thread.sleep(1000);
                                    if(usertype.equals("ADMIN")){
                                        jPanel1.setVisible(false);
                                        adminControls();
                                    }else if(usertype.equals("TECH USER")) {
                                        jPanel1.setVisible(false);
                                        techUserControls();
                                    }
                                } catch (Exception e) {
                                }
                            }
                        };
                        runner2.start();
                    }
                    else{
                        iconm.setVisible(false);
                        message.setForeground(Color.red);
                        message.setText("Invalid Login Details, try again.");
                    }
                }
            };
            runner.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private StaffPersInfo persInfo;
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        Thread runner = new Thread() {

        public void run() {
            persInfo = new StaffPersInfo();
            desktop1.add(persInfo);
        try {
            persInfo.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
        }
        }
            };
        runner.start();
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    private EditContactInfo mandate;
    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Thread runner = new Thread() {

                public void run() {
                    mandate = new EditContactInfo();
                    desktop1.add(mandate);
                    try {
                        mandate.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
            //this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

   private ViewAllStaff viewProf;
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Thread runner = new Thread() {

        public void run() {
            viewProf= new ViewAllStaff();
            desktop1.add(viewProf);
        try {
            viewProf.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            
        }
        }
            };
        runner.start();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    ViewStaffDuePayment mandate6 = new ViewStaffDuePayment();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem12ActionPerformed
    private EditEducationInfo mandate2;
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    mandate2 = new EditEducationInfo();
                    desktop1.add(mandate2);
                    try {
                        mandate2.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem13ActionPerformed
    private EditKinInfo mandate3;
    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    mandate3 = new EditKinInfo();
                    desktop1.add(mandate3);
                    try {
                        mandate3.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem14ActionPerformed
    private EditStaffAccInfo mandate5;
    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    mandate5 = new EditStaffAccInfo();
                    desktop1.add(mandate5);
                    try {
                        mandate5.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem15ActionPerformed
    private EditStaffPersInfo mandate1;
    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    mandate1 = new EditStaffPersInfo();
                    desktop1.add(mandate1);
                    try {
                        mandate1.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    ViewDuePayment mandate6 = new ViewDuePayment();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    ViewStaffMonument mandate6 = new ViewStaffMonument();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    ViewStaffClocking mandate6 = new ViewStaffClocking();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    ViewClocking mandate6 = new ViewClocking();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    ViewStaffsMonument mandate6 = new ViewStaffsMonument();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    StaffSignIn mandate6 = new StaffSignIn();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    StaffSignOut mandate6 = new StaffSignOut();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        Thread runner = new Thread() {

                public void run() {
                    PayStaffPersonal mandate6 = new PayStaffPersonal();
                    desktop1.add(mandate6);
                    try {
                        mandate6.setSelected(true);
                    }catch (java.beans.PropertyVetoException e) {
                    }
                }
            };
            runner.start();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Continue Logout?","Confirm logout",JOptionPane.YES_NO_OPTION);
        if (a==0){
            new MainMenu().setVisible(true);
            this.dispose();
            this.hide();
        }else{

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktop1;
    private javax.swing.JLabel iconm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
