/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import static com.ecs.MainMenu.desktop1;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class PayStaffPersonal extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContactInfo
     */
    public PayStaffPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        validate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        staffId = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        perform = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        monument = new javax.swing.JFormattedTextField();
        staffName = new javax.swing.JTextField();
        refresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pay Staff (Personal)");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(456, 423));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jPanel3.setMinimumSize(new java.awt.Dimension(470, 407));
        jPanel3.setPreferredSize(new java.awt.Dimension(451, 420));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Validate Staff ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        validate.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        validate.setText("Validate");
        validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateActionPerformed(evt);
            }
        });
        jPanel1.add(validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 51));
        jLabel11.setText("Staff ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 40));

        staffId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        staffId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        staffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffIdActionPerformed(evt);
            }
        });
        jPanel1.add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, 20));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 110));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("STAFF DUE PAYMENT");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Payment Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Staff Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Monument Amount");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Amount to Credit");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        perform.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        perform.setText("Perform Deposit");
        perform.setEnabled(false);
        perform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performActionPerformed(evt);
            }
        });
        jPanel2.add(perform, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 160, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 51, 51));
        jLabel34.setText(" *");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 20, 20));

        amount.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, 20));

        monument.setEditable(false);
        monument.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        monument.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(monument, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 130, 20));

        staffName.setEditable(false);
        staffName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 220, 20));

        refresh.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel2.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 390, 160));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 450, 10));

        cancel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 90, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateActionPerformed
        if(staffId.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Empty fields", "Error", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql= "select * from staff_pers_info, staff_acct_bal where staff_pers_info.staff_id= ? AND staff_pers_info.staff_id = staff_acct_bal.staff_id";
                st = DBConnection.con.prepareStatement(sql);
                
                st.setString(1, staffId.getText().trim());
                DBConnection.rs = st.executeQuery();
                
                if (DBConnection.rs.next()){
                    staffName.setText(DBConnection.rs.getString("fname").toUpperCase() +" "+ DBConnection.rs.getString("lname") +" "+ DBConnection.rs.getString("mname"));
                    monument.setText(String.format("%.2f", DBConnection.rs.getDouble("balance")));
                    amount.setText("");
                    perform.setEnabled(true);
                    staffId.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Staff ID does not exist",
                        "Error", JOptionPane.OK_OPTION);
                    staffName.setText("");
                    monument.setText("");
                    amount.setText("");
                }
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_validateActionPerformed

    private void performActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performActionPerformed
        try{
            if(staffName.getText().equals("") || monument.getText().equals("")|| amount.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Empty fields", "Error", JOptionPane.OK_OPTION);
            }else if(Double.parseDouble(amount.getText().replaceAll(",","")) < 0.0){
                JOptionPane.showMessageDialog(this, "Payment amount cannot be less than #0","Error",JOptionPane.OK_OPTION);
            }else if(Double.parseDouble(amount.getText().replaceAll(",","")) > Double.parseDouble(monument.getText().replaceAll(",",""))){
                JOptionPane.showMessageDialog(this, "Amount paid can not be greater than staff monument","Error",JOptionPane.OK_OPTION);
            }else{
                try{
                    PreparedStatement st;
                    String sql= "select * from staff_acct_bal where staff_id= ?";
                    st = DBConnection.con.prepareStatement(sql);
                    st.setString(1, staffId.getText());
                    DBConnection.rs= st.executeQuery();
                    if (DBConnection.rs.next()){
                        double balance=DBConnection.rs.getDouble("balance");
                        double amount = Double.parseDouble(this.amount.getText().replaceAll(",",""));
                        sql ="insert into staff_acct_trans (staff_id, amount_in, amount_out, balance, description) values (?,?,?,?,?)";
                        st= DBConnection.con.prepareStatement(sql);
                        
                        st.setInt(1, Integer.parseInt(staffId.getText()));
                        st.setDouble(2, 0);
                        st.setDouble(3, amount);
                        st.setDouble(4, Double.parseDouble(String.format("%.2f", (balance - amount))));
                        st.setString(5, "Paid for Service");
                        
                        st.executeUpdate();

                        sql = "update staff_acct_bal set balance = ? where staff_id = ?";

                        st = DBConnection.con.prepareStatement(sql);
                        st.setDouble(1, Double.parseDouble(String.format("%.2f", (balance - amount))));
                        st.setString(2, staffId.getText());
                        
                        st.executeUpdate();
                        
                        JOptionPane.showMessageDialog(this, "Staff was paid successfully","Information", JOptionPane.INFORMATION_MESSAGE);
                        refresh();
                    }
                }catch(Exception ex){
                    ex.printStackTrace();
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception ex){
            //System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_performActionPerformed

    public void refresh(){
        this.dispose();
        this.hide();
        
        Thread runner = new Thread() {

            public void run() {
                PayStaffPersonal mandate6 = new PayStaffPersonal();
                desktop1.add(mandate6);
                try {
                    mandate6.setSelected(true);
                }catch (java.beans.PropertyVetoException e) {
                }
            }
        };
        runner.start();
    }
    
    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        refresh();
    }//GEN-LAST:event_refreshActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_cancelActionPerformed

    private void staffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffIdActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField amount;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JFormattedTextField monument;
    public static javax.swing.JButton perform;
    public static javax.swing.JButton refresh;
    public static javax.swing.JFormattedTextField staffId;
    public static javax.swing.JTextField staffName;
    private javax.swing.JButton validate;
    // End of variables declaration//GEN-END:variables
}
