/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class StaffAccInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form StaffAccInfo
     */
    EducationInfo p;
    public StaffAccInfo(EducationInfo e) {
        this.p=e;
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bank = new javax.swing.JComboBox();
        insert = new javax.swing.JButton();
        pay = new javax.swing.JFormattedTextField();
        acctNumb = new javax.swing.JTextField();
        sortCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();

        setClosable(true);
        setTitle("Staff Bank Account Details");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 340, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)), "Staff Bank Account Deteils", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.darkGray)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Acct Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Bank Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 51));
        jLabel7.setText(" Staff Hourly Pay");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("Sort Code");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        bank.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        bank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Bank", "Eco Bank", "First Bank", "GTBank", "MainStreet Bank" }));
        bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankActionPerformed(evt);
            }
        });
        jPanel1.add(bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

        insert.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        insert.setText("Next");
        insert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        pay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        pay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, 20));

        acctNumb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(acctNumb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, 20));

        sortCode.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel1.add(sortCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 20));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 190));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("STAFF INFORMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        cancel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private StaffPersInfo persInfo;
    private void bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_cancelActionPerformed

    public int getStaffID(){
        return p.getStaffID();
    }
    
    public void insert() throws Exception{
        p.insert();

        try{
        
            PreparedStatement st;

            String sql="insert into staff_acct_info (staff_id, acct_numb, bank_name, sort_code, staff_hourly_pay) values (?,?,?,?,?)";
            st= DBConnection.con.prepareStatement(sql);
            st.setString(1, ""+getStaffID());
            st.setString(2, acctNumb.getText());
            st.setString(3, ""+bank.getSelectedItem());
            st.setString(4, sortCode.getText());
            st.setDouble(5, Double.parseDouble(pay.getText().replace(",", "")));
            st.executeUpdate();

            sql="insert into staff_acct_bal (staff_id, balance) values (?,?)";
            st= DBConnection.con.prepareStatement(sql);
            st.setString(1, ""+getStaffID());
            st.setDouble(2, 0.0);
            st.executeUpdate();
            System.out.println("Done5");
        }catch(NumberFormatException nEx){
            JOptionPane.showMessageDialog(this, "Account number or sort code is incorrect","Issues!", JOptionPane.OK_OPTION);
        }
    }
    
    
    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        if(acctNumb.getText().equals("") || sortCode.getText().equals("") || bank.getSelectedIndex()==0 || pay.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Empty Fields", "Empty Fields", JOptionPane.OK_OPTION);
        }else{
            try{
                long acct_num = Long.parseLong(acctNumb.getText());
                long sort_code = Long.parseLong(sortCode.getText());
                Thread runner = new Thread() {

                    public void run() {
                        UploadBio bio = new UploadBio(StaffAccInfo.this);
                        MainMenu.desktop1.add(bio);
                        try {
                            bio.setSelected(true);
                        } catch (java.beans.PropertyVetoException e) {

                        }
                    }
                };
                runner.start();
                this.dispose();
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Account number or sort code is incorrect","Issues!", JOptionPane.OK_OPTION);
                System.err.println(ex.getMessage());
            }catch(Exception ex){
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_insertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField acctNumb;
    public static javax.swing.JComboBox bank;
    private javax.swing.JButton cancel;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JFormattedTextField pay;
    public static javax.swing.JTextField sortCode;
    // End of variables declaration//GEN-END:variables
}
