/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import static com.ecs.MainMenu.desktop1;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author NUHU
 */
public class StaffSignIn extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentRegistration
     */
    public String getRegNo(){
        return this.staff_id.getText();
    }
    
    public StaffSignIn() {
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        staff_id = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Staff Sign In");
        setPreferredSize(new java.awt.Dimension(355, 244));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("STAFF SIGN IN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)), "Sign In Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.darkGray)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Staff ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));
        jPanel1.add(staff_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 220, 20));

        next.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        next.setText("Continue");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, 100));

        cancel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 100, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 340, 10));

        getAccessibleContext().setAccessibleName("Staff Sign In");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String getStaffId(){
        return this.staff_id.getText();
    }
    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if(staff_id.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty fields!", "Issue!", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql = "select * from staff_pers_info where staff_id = ?";
                st = DBConnection.con.prepareStatement(sql);
                st.setString(1, staff_id.getText());
                DBConnection.rs = st.executeQuery();
                if(DBConnection.rs.next()){
                    sql = "select * from staff_sign_in where staff_id = ? and status = 'IN'";
                    st = DBConnection.con.prepareStatement(sql);
                    
                    st.setString(1, staff_id.getText());
                    
                    DBConnection.rs = st.executeQuery();
                    
                    if(DBConnection.rs.next()){
                        JOptionPane.showMessageDialog(this, "Staff has already been signed in.", "Issue", JOptionPane.OK_OPTION);
                    }else{
                        this.dispose();
                        this.hide();
                        Thread runner = new Thread() {

                            public void run() {
                            SignInVerifyBio addUsers= new SignInVerifyBio(StaffSignIn.this);
                                desktop1.add(addUsers);
                                try {
                                    addUsers.setSelected(true);
                                } catch (java.beans.PropertyVetoException e) {
                                }
                            }
                        };
                        runner.start();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Staff does not exist", "Issue", JOptionPane.OK_OPTION);
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Issue");
                System.out.println(ex.getMessage());
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_nextActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton next;
    private javax.swing.JTextField staff_id;
    // End of variables declaration//GEN-END:variables
}
