/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import static com.ecs.MainMenu.desktop1;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
public class ViewStaffMonument extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditCitizenInfo
     */
    public ViewStaffMonument() {
        DBConnection.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        staffId = new javax.swing.JFormattedTextField();
        select9 = new javax.swing.JButton();
        select8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        monument_bal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        amount1 = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel81 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        staffId11 = new javax.swing.JLabel();
        staffName = new javax.swing.JLabel();
        select7 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Staff Monument");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Find16.gif"))); // NOI18N
        setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Staff ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 51));
        jLabel11.setText("Staff ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 30));

        staffId.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        staffId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, 30));

        select9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select9.setText("Refresh");
        select9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select9ActionPerformed(evt);
            }
        });
        jPanel1.add(select9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 30));

        select8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select8.setText("View");
        select8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select8ActionPerformed(evt);
            }
        });
        jPanel1.add(select8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 90, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 110));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("STAFF MONUMENT INFORMATION");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 430, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 102, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 490, 10));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)), "Monument Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tempus Sans ITC", 0, 16))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monument_bal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monument_bal.setEnabled(false);
        jPanel3.add(monument_bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 300, 20));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Current Monument Balance");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(0, 153, 0));
        jLabel77.setText("Date ");
        jPanel3.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Last Sign In Date and Amount");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(0, 153, 0));
        jLabel78.setText("Amount");
        jPanel3.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 50, -1));

        amount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amount.setEnabled(false);
        jPanel3.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 300, 20));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Last Payment Date and Amount");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(0, 153, 0));
        jLabel80.setText("Amount");
        jPanel3.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        amount1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amount1.setEnabled(false);
        jPanel3.add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 300, 20));

        date.setEnabled(false);
        jPanel3.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, -1));

        jLabel81.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(0, 153, 0));
        jLabel81.setText("Date ");
        jPanel3.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        date1.setEnabled(false);
        jPanel3.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 170, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 450, 280));

        staffId11.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        staffId11.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(staffId11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 230, 20));

        staffName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        staffName.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 230, 20));

        select7.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        select7.setText("Cancel");
        select7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        select7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select7ActionPerformed(evt);
            }
        });
        jPanel2.add(select7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static String name;
    private void select7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select7ActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_select7ActionPerformed

    private void select8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select8ActionPerformed
        if(staffId.getText().equals("") ){
            JOptionPane.showMessageDialog(this,"Empty fields", "Empty fields", JOptionPane.OK_OPTION);
        }else{
            try{
                PreparedStatement st;
                String sql= "select * from staff_pers_info, staff_acct_bal where staff_pers_info.staff_id = ? AND staff_pers_info.staff_id = staff_acct_bal.staff_id";
                st = DBConnection.con.prepareStatement(sql);
                st.setInt(1, Integer.parseInt(staffId.getText()));
                DBConnection.rs= st.executeQuery();
                if(DBConnection.rs.next()){
                    staffName.setText(DBConnection.rs.getString("fname") + (DBConnection.rs.getString("mname").equals("") ? " ": " "+DBConnection.rs.getString("mname")+", ") + DBConnection.rs.getString("lname"));
                    staffId11.setText(staffId.getText().trim());
                    monument_bal.setText(""+DBConnection.rs.getDouble("balance"));
                    
                    sql= "select MAX(sign_in_time), amount_in, sign_in_time, date from staff_acct_trans, staff_sign_in where staff_sign_in.staff_id = ? AND staff_sign_in.staff_id = staff_acct_trans.staff_id AND staff_sign_in.status = 'OUT' AND staff_sign_in.sign_out_time = staff_acct_trans.date AND amount_out = 0";
                    st = DBConnection.con.prepareStatement(sql);
                    st.setInt(1, Integer.parseInt(staffId.getText()));
                    DBConnection.rs= st.executeQuery();
                    
                    DBConnection.rs.next();

                    String t = DBConnection.rs.getString("sign_in_time").replaceAll("-", "/");
                    Date date = new Date(t.substring(0, t.length()-2));
                    
                    this.date.setDate(date);
                    amount.setText(DBConnection.rs.getString("amount_in"));
                    
                    sql= "select MAX(date), amount_out, date from staff_acct_trans where staff_id = ? AND amount_in = 0";
                    st = DBConnection.con.prepareStatement(sql);
                    st.setInt(1, Integer.parseInt(staffId.getText()));
                    DBConnection.rs= st.executeQuery();
                    
                    if(DBConnection.rs.next()){
                        t = DBConnection.rs.getString("date").replaceAll("-", "/");
                        date = new Date(t.substring(0, t.length()-2));
                        this.date1.setDate(date);
                        amount1.setText(""+DBConnection.rs.getDouble("amount_out"));
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Staff ID does not exist",
                        "Staff not found", JOptionPane.OK_OPTION);
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, "Error", "Error", JOptionPane.OK_OPTION);
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_select8ActionPerformed

    private void select9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select9ActionPerformed
        refresh();
    }//GEN-LAST:event_select9ActionPerformed

    public void refresh(){
        Thread runner = new Thread() {

            public void run() {
                ViewStaffMonument mandate1 = new ViewStaffMonument();
                desktop1.add(mandate1);
                try {
                    mandate1.setSelected(true);
                }catch (java.beans.PropertyVetoException e) {
                }
            }
        };
        runner.start();
        
        this.dispose();
        this.hide();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount1;
    private com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField monument_bal;
    private javax.swing.JButton select7;
    private javax.swing.JButton select8;
    private javax.swing.JButton select9;
    public static javax.swing.JFormattedTextField staffId;
    private javax.swing.JLabel staffId11;
    private javax.swing.JLabel staffName;
    // End of variables declaration//GEN-END:variables
}
