/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.ecs;

import com.dataStructures.MyTable;
import com.dataStructures.ResultSetTableModel;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SHANMA
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
public class ViewStaffDuePayment extends javax.swing.JInternalFrame {

    /**
     * Creates new form PersonalDetails
     */
    public ViewStaffDuePayment() {
        DBConnection.connect();
        initComponents();
    }

    private JTable table;
    private TableColumn column = null;
    private JScrollPane scrollPane;
    private ResultSetTableModel tableModel;
 
    private void createTable(){
        String fromDate = new SimpleDateFormat("yyyy-MM-dd").format(this.fromDate.getDate());
        String toDate = new SimpleDateFormat("yyyy-MM-dd").format(this.toDate.getDate());
        String staffId = this.staffId.getText();
        
        String sql="SELECT staff_id, amount_in, amount_out, balance, description, date from staff_acct_trans where date between '"+fromDate+"' and '"+toDate+"' AND staff_id = "+staffId+" ORDER BY date DESC";
        
        JTable table;
        TableColumn column = null;
        JScrollPane scrollPane;
        String meta[]={"Staff ID", "Amount In", "Amount Out", "Balance", "Descripton", "Date"};
        table= MyTable.createTable(sql, meta);
        table.setPreferredScrollableViewportSize(new Dimension(570, 200));
        scrollPane = new JScrollPane(table);
      
        contentPanel.removeAll();
        scrollPane.setViewportView(table);
        contentPanel.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 200));
        contentPanel.setVisible(false);
        contentPanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        uDemo16 = new javax.swing.JLabel();
        uDemo17 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        uDemo18 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        fromDate = new com.toedter.calendar.JDateChooser();
        staffId = new javax.swing.JTextField();
        contentPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        compute1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Staff Due Transaction");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/user32.jpg"))); // NOI18N
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(588, 418));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 12, 92)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uDemo16.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo16.setForeground(new java.awt.Color(0, 0, 102));
        uDemo16.setText("From (Date)");
        jPanel2.add(uDemo16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        uDemo17.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo17.setForeground(new java.awt.Color(0, 0, 102));
        uDemo17.setText("To (Date)");
        jPanel2.add(uDemo17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 30));

        generate.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        generate.setText("Generate Report");
        generate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        jPanel2.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 170, 35));

        uDemo18.setFont(new java.awt.Font("Simplified Arabic Fixed", 0, 18)); // NOI18N
        uDemo18.setForeground(new java.awt.Color(0, 0, 102));
        uDemo18.setText(" Staff ID");
        jPanel2.add(uDemo18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));
        jPanel2.add(toDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, -1));
        jPanel2.add(fromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        staffId.setFont(new java.awt.Font("Tempus Sans ITC", 0, 13)); // NOI18N
        jPanel2.add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 460, 140));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 570, 200));

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("STAFF PAYMENT INFORMATION");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tiger Expert", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REPORT");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 590, -1));

        compute1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        compute1.setText("Close");
        compute1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        compute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compute1ActionPerformed(evt);
            }
        });
        jPanel1.add(compute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 170, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        this.hide();
        this.dispose();
    }//GEN-LAST:event_formInternalFrameDeactivated

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        if(this.toDate.getDate()==null || this.fromDate.getDate()==null || staffId.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty Fields", "Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-197-exclamation-sign.png")));
        }else{
            try{
                String fromDate = new SimpleDateFormat("yyyy-MM-dd").format(this.fromDate.getDate());
                String toDate = new SimpleDateFormat("yyyy-MM-dd").format(this.toDate.getDate());
                String staffId = this.staffId.getText();
                PreparedStatement st;
                st = DBConnection.con.prepareStatement("select * from staff_pers_info where staff_id = ?");
                st.setString(1, staffId);
                
                DBConnection.rs = st.executeQuery();
                if(DBConnection.rs.next()){
                    String sql="select * from staff_acct_trans where date between ? and ? AND  staff_acct_trans.staff_id = ?";
                    st=DBConnection.con.prepareStatement(sql);
                    st.setString(1, fromDate);
                    st.setString(2, toDate);
                    st.setString(3, staffId);

                    DBConnection.rs=st.executeQuery();

                    if(DBConnection.rs.next()){
                        createTable();
                    }else{
                        JOptionPane.showMessageDialog(this, "No record exist for the period specified","Information!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-196-info-sign.png")));
                        createTable();
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Staff Id does not exist","Information!", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-196-info-sign.png")));
                }
            }catch(SQLException sqlEx){
                JOptionPane.showMessageDialog(this, "Issues excecuting query","Issue!", JOptionPane.OK_OPTION, new javax.swing.ImageIcon(getClass().getResource("/com/images/glyphicons-197-exclamation-sign.png")));
                createTable();
            }
        }
    }//GEN-LAST:event_generateActionPerformed

    private void compute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compute1ActionPerformed
        this.dispose();
        this.hide();
    }//GEN-LAST:event_compute1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compute1;
    public static javax.swing.JPanel contentPanel;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JTextField staffId;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JLabel uDemo16;
    private javax.swing.JLabel uDemo17;
    private javax.swing.JLabel uDemo18;
    // End of variables declaration//GEN-END:variables
}
